name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy
        pip install -r requirements.txt
    
    - name: Format check with black
      run: black --check .
    
    - name: Lint with flake8
      run: flake8 . --max-line-length=100 --exclude=venv,__pycache__
    
    - name: Type check with mypy
      run: mypy . --ignore-missing-imports

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run unit tests
      run: |
        pytest tests/unit -v --cov=namenode --cov=datanode --cov=client
    
    - name: Run integration tests
      run: |
        pytest tests/integration -v

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build NameNode image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/namenode.Dockerfile
        tags: dfs-namenode:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build DataNode image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/datanode.Dockerfile
        tags: dfs-datanode:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build Client image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/client.Dockerfile
        tags: dfs-client:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test Docker Compose
      run: |
        docker-compose up -d
        sleep 10
        docker-compose ps
        docker-compose logs
        docker-compose down